version: "3.7"

services:

  cockroach-1:
    image: cockroachdb/cockroach:v21.2.0
    ports:
      - 8089:8080
      - 26257:26257
    networks:
      - cockroach-net
    volumes:
      - type: volume
        source: cockroach-1-data
        target: /cockroach/cockroach-data
    container_name: cockroach_1_server
    command:
      - start
      - --insecure
      - --join=cockroach-1,cockroach-2,cockroach-3

  cockroach-2:
    image: cockroachdb/cockroach:v21.2.0
    networks:
      - cockroach-net
    volumes:
      - type: volume
        source: cockroach-2-data
        target: /cockroach/cockroach-data
    container_name: cockroach_2_server
    command:
      - start
      - --insecure
      - --join=cockroach-1,cockroach-2,cockroach-3

  cockroach-3:
    image: cockroachdb/cockroach:v21.2.0
    networks:
      - cockroach-net
    volumes:
      - type: volume
        source: cockroach-3-data
        target: /cockroach/cockroach-data
    container_name: cockroach_3_server
    command:
      - start
      - --insecure
      - --join=cockroach-1,cockroach-2,cockroach-3
  db-init:
    image: cockroachdb/cockroach:v21.2.0
    volumes:
      - ./initdb.sql:/initdb.sql
      - ./tables.sql:/tables.sql
    depends_on:
      - cockroach-1
      - cockroach-2
      - cockroach-3
    networks:
      - cockroach-net
    entrypoint: /bin/bash
    command: >
      -c "
      until cockroach sql --insecure --host=cockroach-1 --execute='SELECT 1'; do
        echo 'Waiting for CockroachDB to become ready...'
        sleep 1
      done;
      echo 'CockroachDB is up - executing command';
      cockroach sql --insecure --host=cockroach-1 -f /initdb.sql;
      cockroach sql --insecure --host=cockroach-1 -f /tables.sql;
      "
    container_name: cockroach_db_init

volumes:
  cockroach-1-data:
  cockroach-2-data:
  cockroach-3-data:

networks:
  cockroach-net:
    driver: bridge